#spring:
#  mustache:
#    servlet:
#      expose-request-attributes: true
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # Google Cloud Dashboard -> APIs & Service -> Credentials -> OAuth 2.0 Client IDs
            clientId: XXXXXXXXXX.apps.googleusercontent.com
            clientSecret: GOCSPX-YYYYYYYYYY
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube
logging:
  level:
    io.spring.shinyay.learningspringboot3.ch4: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
