spring:
  mustache:
    servlet:
      expose-request-attributes: true
logging:
  level:
    io.spring.shinyay.learningspringboot3.ch6: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
app:
  config:
    header: Greetings Learning Spring Boot 3.0 fans!
    intro: In this chapter, we are learning how to externalize using property files.
    users[0]:
      username: alice
      password: password
      authorities[0]: ROLE_USER
    users[1]:
      username: bob
      password: password
      authorities[0]: ROLE_USER
    users[2]:
      username: admin
      password: password
      authorities[0]: ROLE_ADMIN
