spring:
  mustache:
    servlet:
      expose-request-attributes: true
logging:
  level:
    io.spring.shinyay.learningspringboot3.ch6: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
app:
  config:
    header: Greetings Test Team!
    intro: If you run into issues while testing, let me know!
    users:
      -
        username: test1
        password: password
        authorities:
          - ROLE_NOTHING
      -
        username: test2
        password: password
        authorities:
          - ROLE_USER
      -
        username: test3
        password: password
        authorities[0]:
          - ROLE_ADMIN
