spring:
  mustache:
    servlet:
      expose-request-attributes: true
logging:
  level:
    io.spring.shinyay.learningspringboot3.ch6: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
app:
  config:
    header: Greetings Learning Spring Boot 3.0 fans!
    intro: In this chapter, we are learning how to externalize using property files.
    users:
      -
        username: alice
        password: password
        authorities:
          - ROLE_USER
      -
        username: bob
        password: password
        authorities:
          - ROLE_USER
      -
        username: admin
        password: password
        authorities[0]:
          - ROLE_ADMIN
